### ISSUE TITLE
Docker image support 

### ISSUE THREAD

**Issue by harikant-lftt** [sweid4keycloak/bankid4keycloak#37]
I wanted to understand how I can use this package with keyclock which is running under container. I don't have stand alone server of keyclock. My KC is running in side k8s

Thank you!

**Comment by isrjo** [comment]
Why not give our image a try ? It's basically a wrapper around the official keycloak image with bankid provider bundled.
https://github.com/sweid4keycloak/bankid4keycloak/pkgs/container/bankid4keycloak

More infomation about the keycloak image is avalible at https://www.keycloak.org/getting-started/getting-started-docker

**Comment by harikant-lftt** [comment]
Thank you!, I will give a try

**Comment by harikant-lftt** [comment]
Hi @isrjo 
I have tried using this image but my container is stuck with below message

**Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.**


I am running the image with below details

version: '3.8'

services:
  keycloak:
    image: ghcr.io/sweid4keycloak/bankid4keycloak:master  
    environment:
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_DB: 'postgres'
      KC_DB_URL: jdbc:postgresql://${POSTGRES_INFRA_DB_HOST}/${KEYCLOAK_DB_DATABASE}?&sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_ADMIN: ${KC_HOSTNAME} 
      KC_HOSTNAME_STRICT: 'true'
      KC_HOSTNAME_STRICT_HTTPS: 'false' 
      KC_HOSTNAME_STRICT_BACKCHANNEL: 'true'
      KC_HTTPS_CERTIFICATE_FILE: '/opt/certs/conf/keys/ca.pem'
      KC_HTTPS_CERTIFICATE_KEY_FILE: '/opt/certs/conf/keys/ca.key'
    command: start
    ports:
      - 8443:8443 
    networks:
      - alf-overlay-nw
    volumes:
      - ${SSL_CERTS_LOCATION:-/certs}:/opt/certs/conf/keys

networks:
  alf-overlay-nw:
    external: true

**Comment by harikant-lftt** [comment]
2023-07-04 10:13:12 Updating the configuration and installing your custom providers, if any. Please wait.
2023-07-04 10:14:17 2023-07-04 08:14:17,589 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 58314ms
2023-07-04 10:14:17 Server configuration updated and persisted. Run the following command to review the configuration:
2023-07-04 10:14:17 
2023-07-04 10:14:17     kc.sh show-config
2023-07-04 10:14:17 
2023-07-04 10:14:17 Next time you run the server, just run:
2023-07-04 10:14:17 
2023-07-04 10:14:17     kc.sh start --optimized 
2023-07-04 10:14:17 


I rung this today, it is stuck at this point.

@isrjo

**Comment by qvicksilver** [comment]
@harikant-lftt Could you please provide the exact command you are using to start the container?

**Comment by harikant-lftt** [comment]
I was using docker compose  file than I used docker compose up -d to spin up the container.

I figure the image you publish was not using build command after copy the jar file.

Now I have created my own Dockerfile and publish a new image  and it is working
