### ISSUE TITLE
How to use bankid client certificate with docker image 

### ISSUE THREAD

**Issue by harikant-lftt** [sweid4keycloak/bankid4keycloak#42]
Hey,

May be I have missed the documentation, but I am struggling to use bankid client certificate(test.ca) and FPTestcert4_20220818.p12 with docker image, How I can put these two file in truststore of  docker image

**Comment by qvicksilver** [comment]
What part of using them is problematic?

Does [this](https://github.com/sweid4keycloak/bankid4keycloak/pkgs/container/bankid4keycloak#client-certificate-and-truststore) answer your questions?

**Comment by ullgren** [comment]
To make them available inside the docker container there are several options.

The simplest, in my opinion, is to place them in a local folder and then mount that folder as a volume when starting docker.

Lets say you place the p12 files in your Downloads directory in your home folder

```
docker run -p 8080:8080 -v /home/ponu/Downloads/:/certs ghcr.io/sweid4keycloak/bankid4keycloak:master start-dev
```

You can then use the path `/certs/FPTestcert4_20220818.p12`  when configuring the provides inside the running container.

**Comment by harikant-lftt** [comment]
Thank you @ullgren

**Comment by harikant-lftt** [comment]
Closing this bug. I was able to figure out what mistake I was doing.

Thank you !!
