### ISSUE TITLE
Storing SSN without user modification

### ISSUE THREAD

**Issue by mikaelkaron** [sweid4keycloak/bankid4keycloak#57]
First - Love the provider! Nice to see someone give BankID some love.

So I've managed to set up bankid for test and successfully authenticated, and upon first login I get sent to the registration UI. Now:

- the username is pre-filled with my ssn, is there a way to store this on the profile _without_ allowing the user to modify?

- preferably I would like to remove the username field entirely as my app relies on login via email/bankid, is this possible?

- is it possible to push the users ssn all the way into the authtoken?

I'm guessing some of these are more generic Keycloak questions but I figured I'd ask here first. 

Tack på förhand!

**Comment by ullgren** [comment]
First: Thanks :-)

We do note have a attribute mapper, see #12. However the SSN is stored in the users "Identity Provider Links".
In addition to this the SSN and many other details from the BankID response, is also [stored in the authentication session user notes](https://github.com/sweid4keycloak/bankid4keycloak/blob/master/src/main/java/org/keycloak/broker/bankid/BankidEndpoint.java#L191-L198).   
In the Client Scope you can then use a "User Session Note" mapper to map any of these into the authtoken.
We store the SSN under the key `<name of the idp>.pnr` by default the name is set to `bankid` so adding something like this would store the SSN in a claim called ssn in the authoken.
![image](https://github.com/user-attachments/assets/b3a1de66-c182-424b-a794-dd9a8dde80ea)
 
 
To my knowledge you can not remove the username in keycloak, but using the new profile support (I think it was added in 24 or possibly 25) you can control if the user can see and/or edit the username. Check the Realm Settings under "User Profile".


Let me know if this helped or if you have further questions.

**Comment by mikaelkaron** [comment]
This all worked perfectly! Tack så jätte mycket!
